// Single source of truth for the portfolio. build.js turns this into static pages,
// and the chatbot's knowledge base is generated from it too.
const GH = 'https://github.com/saad7420/';

const profile = {
  name: 'Saad Mehmood',
  role: 'AI/ML Engineer',
  location: 'Islamabad, Pakistan · working remotely worldwide',
  email: 'mehmoodsaad042@gmail.com',
  github: 'https://github.com/saad7420',
  linkedin: 'https://www.linkedin.com/in/msaadmehmood/',
  x: 'https://x.com/saadmehmood_',
  site: 'https://oqvera.netlify.app',
  formEndpoint: 'https://hook.eu1.make.com/1xbd6mt18cvllho7k1ergevtftc8wj97',
  education: 'BS Artificial Intelligence, COMSATS University Islamabad (2023–2027)',
  bio: [
    "I'm an AI/ML engineer who builds systems that do real work: agents that answer calls and qualify leads, retrieval pipelines that cite their sources, and computer-vision models that run behind a real API.",
    "Most of my work sits where models meet production — orchestration with LangGraph, retrieval with FAISS and ChromaDB, inference behind FastAPI with queues and caching, and the automations (Make, n8n, Vapi) that connect it all to the tools a business already uses.",
    "I also founded OQVERA, a small studio where I design AI automation and agent systems for businesses.",
  ],
};

const skills = [
  { group: 'AI engineering', items: ['LangGraph', 'LangChain', 'RAG', 'Tool calling', 'Structured outputs', 'Pydantic', 'Groq / Llama 3', 'OpenAI', 'Hugging Face', 'Gemini'] },
  { group: 'Retrieval & data', items: ['FAISS', 'ChromaDB', 'Sentence-Transformers', 'Tavily', 'PostgreSQL', 'SQLite', 'MongoDB', 'Redis', 'SQLAlchemy'] },
  { group: 'Deep learning & vision', items: ['PyTorch', 'TensorFlow / Keras', 'ViT & ViViT', 'LoRA fine-tuning', 'U-Net', 'CNN-LSTM', 'MTCNN', 'OpenCV', 'scikit-learn'] },
  { group: 'Backend & infra', items: ['Python', 'FastAPI', 'Flask', 'Django REST', 'Celery', 'Docker', 'Express', 'Node.js', 'TypeScript'] },
  { group: 'Frontend', items: ['React', 'Next.js', 'Vite', 'Tailwind', 'three.js', 'Streamlit'] },
  { group: 'Automation & voice', items: ['Make', 'n8n', 'Zapier', 'Vapi voice agents', 'Webhooks', 'CRM integrations'] },
];

const experience = [
  { when: '2026 – now', what: 'Founder, OQVERA', where: 'AI automation & agent studio', note: 'Design and build voice agents, RAG assistants and workflow automation for businesses, starting with auto dealerships.' },
  { when: '2024 – now', what: 'Web & App Developer', where: 'Omni Digitals', note: 'WordPress sites and cross-platform apps for client businesses, from build to SEO and maintenance.' },
  { when: '2023 – 2027', what: 'BS Artificial Intelligence', where: 'COMSATS University Islamabad', note: 'Neural networks, computer vision and machine learning; several projects below began as coursework and grew from there.' },
];

// kinds drive the filters on the projects page
const KINDS = { agents: 'AI agents', rag: 'RAG & documents', vision: 'Computer vision', ml: 'Machine learning', web: 'Web & AR', automation: 'Automation' };

const projects = [
  {
    slug: 'deeptruth', featured: true, caseStudy: true, kind: ['vision', 'ml'], year: '2026',
    title: 'DeepTruth', subtitle: 'Deepfake and synthetic-media detection platform',
    oneLiner: 'Upload a video or image and get a verdict on whether it was manipulated, from an ensemble of fine-tuned vision transformers running behind a queued API, a web console and a browser extension.',
    links: { github: GH + 'Deep-Truth---DeepFake-Media-Detection' },
    stack: ['PyTorch', 'ViViT', 'ViT-B/16', 'LoRA', 'MTCNN', 'FastAPI', 'Celery', 'Redis', 'SQLite', 'Server-Sent Events', 'Next.js 16', 'Chrome extension'],
    numbers: [{ v: '14', l: 'LoRA adapters in the ensemble' }, { v: '3', l: 'clients: console, extension, CLI' }, { v: '1 GET', l: 'to replay a cached verdict' }],
    problem: 'Detecting manipulated media is slow and expensive: a single video analysis takes minutes of transformer inference. In the first version, one upload blocked the API for everyone else, the same viral clip was analysed again every time someone checked it, and image cases simply came back "not implemented".',
    approach: [
      'The pipeline probes each upload, preprocesses it per modality, then runs specialist models. Video goes through frame extraction and MTCNN face crops into six ViViT checkpoints with LoRA adapters; the verdict takes the stronger of the face-average and generated-video signals, gated by how many frames actually contained a trustworthy face. Images go through eight ViT-B/16 LoRA adapters — five generalists and three face specialists with their own MTCNN crop branch.',
      'Inference moved out of the API process. POST /cases hashes the bytes with SHA-256 and checks Redis first: a hit replays the stored verdict before the response is even sent, a miss publishes a Celery job. Workers prefetch one job at a time so a free worker is never starved by one hoarding long jobs, retry transient failures with exponential backoff and jitter, and fail fast on errors retrying can\'t fix.',
      'Every state change (queued, running, retrying, succeeded, failed, cached) streams to the console over SSE. The Chrome extension can ask the cache by URL before downloading anything, so a repeat sighting costs one GET instead of a download, upload and wait.',
    ],
    flow: ['Upload or URL', 'SHA-256 + Redis cache', 'Celery queue', 'Preprocess: frames, MTCNN faces', 'ViViT / ViT-B/16 + LoRA ensemble', 'Verdict, PDF report, SSE update'],
    features: ['Video and image analysis with modality-specific ensembles', 'Content-hash cache with URL index and version-based invalidation', 'Parallel Celery workers with late acks, so a killed worker\'s job is redelivered, not lost', 'Live job status over Server-Sent Events', 'Case history in SQLite with downloadable PDF reports', 'Rate limiting, media type checks and safe URL fetching', 'Next.js console, Chrome extension and a CLI on the same pipeline'],
    decisions: [
      ['One pipeline, imported everywhere', 'The server used to carry a vendored copy of the pipeline that had drifted and lacked image support. Merging to a single package fixed both at once.'],
      ['Concurrency bounded by RAM, not cores', 'Each worker process loads its own transformer checkpoints, so capacity is planned around memory; two slots is the default on a CPU-only machine.'],
      ['Cache invalidation by version', 'A cached verdict is only wrong if the models change, so bumping one version number retires every entry at once.'],
    ],
    limits: 'Audio detection is wired in as a stub (WavLM integration in progress) and currently returns zero confidence rather than a guess.',
  },
  {
    slug: 'dealership-ai-agent', featured: true, caseStudy: true, kind: ['agents', 'automation'], year: '2026', client: true,
    title: 'Dealership AI Calling Agent', subtitle: 'Voice agent and sales automation for National Motors',
    oneLiner: 'An inbound voice agent for a car dealership that talks to callers, checks live inventory, qualifies the lead, books a test drive and triggers follow-up automatically.',
    links: { contact: true },
    stack: ['Vapi', 'Voice AI', 'Make', 'Google Sheets', 'Webhooks', 'CRM', 'APIs'],
    numbers: [{ v: '24/7', l: 'inbound calls answered' }, { v: '7', l: 'steps from call to follow-up' }, { v: '0', l: 'manual hand-offs in the flow' }],
    problem: 'Dealerships lose buyers in the gap between a call and a callback: after-hours calls go to voicemail, staff are busy on the floor, and leads that do get written down are rarely followed up on time.',
    approach: [
      'A Vapi voice agent answers inbound calls and holds a natural conversation to find out what the caller wants — make, model, budget, timing. While the call is live it queries the dealership\'s vehicle inventory through a Make scenario, so it can say what is actually in stock and at what price.',
      'Once the caller is qualified, the same workflow writes the lead to the CRM, books a test drive and schedules follow-up messages. Every step is a webhook-driven Make module, so the dealership\'s existing tools stay the source of truth.',
    ],
    flow: ['Customer call', 'Vapi voice agent', 'Live inventory lookup', 'Lead qualification', 'CRM record', 'Test-drive booking', 'Automated follow-up'],
    features: ['Natural conversational lead qualification', 'Real-time make, model, price and stock search', 'Automated test-drive scheduling', 'Lead routing and follow-up automation', 'Business data connected through Make and webhooks'],
    decisions: [
      ['Inventory stays where staff already maintain it', 'The agent reads a sheet the sales team already updates, so there is no second system to keep in sync.'],
      ['Automation outside the model', 'The voice agent decides what the caller needs; Make performs the actions. That keeps business rules auditable and editable without touching prompts.'],
    ],
    limits: 'Client project: the code is private. Ask for a live demo using the form below.',
  },
  {
    slug: 'content-creation-pipeline', featured: true, caseStudy: true, kind: ['agents'], year: '2026',
    title: 'Content Creation Pipeline', subtitle: 'Agentic writing workflow with a quality gate, built on LangGraph',
    oneLiner: 'Turns a topic into a researched, outlined, drafted, reviewed and publish-ready post — and sends weak drafts back for revision before anything is published.',
    links: { github: GH + 'Content-Creation-Pipeline-using-LangGraph' },
    stack: ['LangGraph', 'LangChain', 'Groq', 'Llama 3.3 70B', 'Pydantic', 'Python'],
    numbers: [{ v: '6', l: 'workflow stages' }, { v: '7/10', l: 'score needed to publish' }, { v: '2', l: 'revision cycles at most' }],
    problem: 'One-shot prompting produces content that reads fine at a glance but has no research behind it and no editorial check. Nothing stops a weak first draft from going out.',
    approach: [
      'The process is modelled as a LangGraph state machine over a shared state: research notes, outline, draft, feedback, quality score, revision count and history. Each node reads what earlier stages produced and returns only the fields it changes.',
      'After drafting, an evaluator with structured output (a Pydantic schema) returns a score, written feedback and a pass flag. A conditional edge publishes drafts scoring 7 or more and routes the rest to a revision node that rewrites against the feedback, then back to review — capped at two revisions so the loop always ends. Every draft and its feedback is kept in the revision history.',
    ],
    flow: ['Topic', 'Research', 'Outline', 'Draft', 'Structured review', 'Revise ↺ or publish'],
    features: ['Topic-driven research stage', 'Outline separated from drafting for structure', 'Structured quality evaluation: score, feedback, pass', 'Conditional revision loop with a safety limit', 'Revision history preserved', 'Mermaid graph visualisation of the workflow', 'Batch generation from a list of topics'],
    decisions: [
      ['Structured evaluation, not free-text', 'A typed score and pass flag make routing deterministic; the model\'s opinion becomes a branch condition.'],
      ['Bounded loop', 'Revision stops after two cycles even if the score never passes, so cost and latency have a ceiling.'],
    ],
  },
  {
    slug: 'langgraph-tool-agent', featured: true, caseStudy: true, kind: ['agents'], year: '2026',
    title: 'LangGraph Tool-Using Chatbot', subtitle: 'Stateful agent with six live tools and persistent threads',
    oneLiner: 'A chat agent that decides when to search the web, check a stock, get the weather, do maths or convert units — and remembers every conversation thread across restarts.',
    links: { github: GH + 'Chatbot-based-on-Langgraph', demo: 'https://saad7420-chatbot-based-on-langgraph-app-utzuat.streamlit.app/' },
    stack: ['LangGraph', 'LangChain', 'Groq', 'Llama 3.3 70B', 'SQLite checkpointer', 'Streamlit', 'DuckDuckGo', 'OpenWeather', 'Alpha Vantage'],
    numbers: [{ v: '6', l: 'tools the agent can call' }, { v: '∞', l: 'threads saved to SQLite' }, { v: 'Live', l: 'token streaming in the UI' }],
    problem: 'A single-prompt chatbot can\'t look anything up, forgets the conversation on refresh, and makes up numbers it should calculate.',
    approach: [
      'The agent is a LangGraph graph: a chat node calls Llama 3.3 70B with tools bound, and a conditional edge routes to a ToolNode whenever the model asks for one, then back to the chat node to use the result. Each tool has a Pydantic input schema so the model produces valid arguments.',
      'A SqliteSaver checkpointer stores every thread, so the Streamlit sidebar can list past conversations and resume any of them. Responses stream token by token.',
    ],
    flow: ['User message', 'Chat node (Llama 3.3 70B)', 'Tool needed?', 'Tool node: search, stocks, weather, maths', 'Answer streamed', 'Thread saved to SQLite'],
    features: ['Web search, calculator, stock price, weather, date/time and unit conversion tools', 'Typed tool arguments with Pydantic', 'Persistent multi-thread memory with a SQLite checkpointer', 'Conversation list and resume in the sidebar', 'Streaming responses', 'Graph diagram generated from the compiled workflow'],
    decisions: [['Tools over guessing', 'Low temperature (0.1) and a system prompt that demands valid JSON for tool calls keep the model from inventing answers it can fetch.']],
  },
  {
    slug: 'ai-customer-support-platform', caseStudy: true, kind: ['agents'], year: '2026',
    title: 'AI Customer Support Platform', subtitle: 'Production-style support chatbot API with sessions and tests',
    oneLiner: 'A FastAPI service that runs support conversations with memory, stores every session and message, rate-limits clients and ships with Docker and a 90% coverage test gate.',
    links: { github: GH + 'AI-CUSTOMER-SUPPORT-CHATBOT' },
    stack: ['FastAPI', 'LangChain', 'Groq', 'Llama 3.1 8B', 'SQLAlchemy', 'SQLite', 'Pydantic v2', 'Streamlit', 'Docker Compose', 'pytest'],
    numbers: [{ v: '60/min', l: 'rate limit per client' }, { v: '90%', l: 'test coverage threshold' }, { v: '4', l: 'REST endpoints' }],
    problem: 'Demo chatbots keep history in memory, so a restart wipes every conversation, nothing is auditable, and there is no contract for other apps to integrate with.',
    approach: [
      'A REST API creates sessions, accepts messages and returns history. Each user message is saved first, then the full history is replayed into a LangChain conversation chain on Groq, and the reply is stored before it is returned — so the database is always the record of the conversation.',
      'Middleware logs every request and enforces 60 requests a minute. Pydantic v2 schemas define the contract, a Streamlit UI consumes the same API, and Docker Compose starts both with one command. The test suite mocks the model and fails the build below 90% coverage.',
    ],
    flow: ['Streamlit UI', 'FastAPI + rate limit', 'Save message', 'Replay history into chain', 'Groq Llama 3.1', 'Store reply, return'],
    features: ['Session, message and history endpoints', 'Conversation memory rebuilt from the database', 'Request logging and rate limiting middleware', 'Swagger and ReDoc docs, Postman collection', 'Docker images for API and UI', 'Tests for sessions, messages, history, service and rate limits'],
    decisions: [['Persist before you generate', 'Saving the user message before the model call means a failed generation never loses what the customer said.']],
  },
  {
    slug: 'hybrid-research-engine', caseStudy: true, kind: ['rag', 'agents'], year: '2026',
    title: 'Enterprise Document Intelligence', subtitle: 'Hybrid research engine that routes between internal documents and the live web',
    oneLiner: 'Ask a question and an LLM router decides whether to search internal documents, the web, or both — then writes a report where every fact carries a numbered citation.',
    links: { github: GH + 'Enterprise-Document-Intelligence-Platform' },
    stack: ['FastAPI', 'ChromaDB', 'OpenAI embeddings', 'Tavily search', 'Llama 3.2 (HF router)', 'GPT-4o mini', 'Pydantic', 'Streamlit'],
    numbers: [{ v: '3', l: 'routes: local, web, hybrid' }, { v: '6', l: 'top-ranked sources per report' }, { v: '600/120', l: 'chunk size / overlap' }],
    problem: 'Internal knowledge bases go stale and web search knows nothing about your company. Teams end up checking both by hand and pasting results together without sources.',
    approach: [
      'A router model classifies each query as local, web or hybrid using structured output with a confidence score and reasoning; every decision is logged to a JSONL audit file.',
      'Local retrieval uses ChromaDB with text-embedding-3-small over 600-character chunks with 120 overlap; web retrieval uses Tavily. Results are merged into one schema, ranked by score, and the top six become numbered context for a report generator that must cite every major fact inline and end with a sources appendix.',
    ],
    flow: ['Query', 'LLM router: local / web / hybrid', 'ChromaDB + Tavily retrieval', 'Merge and rank', 'Cited report', 'Routing log'],
    features: ['Structured routing with confidence and reasoning', 'Document ingestion with chunking and embeddings', 'Real-time web retrieval', 'Inline numbered citations and sources appendix', 'Routing decisions logged for audit'],
  },
  {
    slug: 'intelligent-document-processing', caseStudy: true, kind: ['rag'], year: '2026',
    title: 'Intelligent Document Processing', subtitle: 'Turn PDFs and Word files into structured, validated data',
    oneLiner: 'Upload a PDF, DOCX or text file and get back a summary, key terms, named entities and action items with owners and due dates — validated against a schema and stored.',
    links: { github: GH + 'Intelligent-Document-Processing-Pipeline' },
    stack: ['FastAPI', 'PyMuPDF', 'python-docx', 'Llama 3.2 (HF router)', 'Pydantic', 'SQLAlchemy', 'Streamlit'],
    numbers: [{ v: '3', l: 'file types parsed' }, { v: '4', l: 'structured outputs per document' }, { v: '12k', l: 'characters analysed per pass' }],
    problem: 'Contracts, meeting notes and reports hold tasks and deadlines that someone has to read and re-type into a tracker.',
    approach: [
      'A parser extracts text from PDF (PyMuPDF), DOCX and TXT. An extraction agent prompts the model with the exact JSON shape required, cleans any stray markdown fences, and validates the result with Pydantic, with a fallback load if the structure is slightly off.',
      'Results are saved through SQLAlchemy and exposed at /api/v1/documents; a Streamlit frontend handles upload and browsing.',
    ],
    flow: ['Upload file', 'Parse PDF / DOCX / TXT', 'LLM extraction', 'Pydantic validation', 'Store in database', 'Summary, entities, action items'],
    features: ['Summary in three to four sentences', 'Key terms', 'Entities typed as person, organisation or location', 'Action items with assignee and due date', 'Document history API'],
  },
  {
    slug: 'product-manual-assistant', caseStudy: true, kind: ['rag'], year: '2026',
    title: 'Product Manual Assistant', subtitle: 'RAG assistant that answers from technical documentation, with page citations',
    oneLiner: 'Engineers ask in plain language about installation, ports or troubleshooting, and get an answer grounded in the manual with the exact source file and page.',
    links: { github: GH + 'Product-Manual-Assistant' },
    stack: ['LangChain', 'FAISS', 'all-MiniLM-L6-v2', 'PyPDF', 'Hugging Face', 'Streamlit'],
    numbers: [{ v: '3', l: 'chunks retrieved per answer' }, { v: '600/120', l: 'chunk size / overlap' }, { v: 'Page', l: 'level citations' }],
    problem: 'Technical manuals are long PDFs. Finding the right port number or recovery step means scrolling, and general chatbots happily invent configuration values.',
    approach: [
      'The manual is loaded page by page, split recursively on paragraphs, sentences then words (600 characters, 120 overlap) so steps stay intact, embedded with all-MiniLM-L6-v2 and stored in a FAISS index. Each chunk keeps its source and page metadata.',
      'At question time the top three chunks become labelled context. The prompt forbids assumptions and requires a fixed "not found in the manual" reply when the answer isn\'t there; the UI shows expandable citations so users can verify.',
    ],
    flow: ['Question', 'Embed query', 'FAISS top-3 chunks', 'Grounded prompt', 'Answer + file and page', 'Fallback if not found'],
    features: ['Natural-language queries over a PDF manual', 'Page-level source attribution', 'Expandable citation panel', 'Strict no-guessing prompt with a fixed fallback', 'Clear errors when the index needs rebuilding'],
  },
  {
    slug: 'smart-form-filler', caseStudy: true, kind: ['agents'], year: '2026',
    title: 'Smart Form Filler', subtitle: 'Agent that turns a sentence into a validated registration form',
    oneLiner: 'Describe an event registration in plain words; the agent extracts the fields, asks one clear question about anything missing, and only emits JSON once it passes validation.',
    links: { github: GH + 'Event-Form-Filling-powered-by-pydantic-output-parser-and-RegEx' },
    stack: ['Python', 'Pydantic v2', 'Regex extraction', 'LangChain structured output (drop-in)', 'Groq'],
    numbers: [{ v: '10/10', l: 'test cases passing' }, { v: '4', l: 'agent stages' }, { v: '0', l: 'API keys needed to run' }],
    problem: 'Free-text sign-ups are full of gaps and typos, and forms that reject input without explaining why make people give up.',
    approach: [
      'An intent classifier first confirms the message is a registration. A form filler extracts fields, a clarification agent finds missing required fields and asks one specific question (or a short combined list), and a Pydantic v2 schema type-, range- and enum-checks the result before it counts as done.',
      'Extraction is deterministic and rule-based so the project runs and tests offline; the backend file includes a drop-in replacement using Groq with structured output against the same function signature.',
    ],
    flow: ['Plain-language input', 'Intent check', 'Field extraction', 'Clarifying question', 'Pydantic validation', 'JSON output'],
    features: ['Intent classification before extraction', 'Targeted clarifying questions', 'Schema validation with types, ranges and enums', 'Interactive CLI', 'Test harness with a generated validation report'],
  },
  {
    slug: 'smart-faq-chatbot', caseStudy: true, kind: ['rag'], year: '2026',
    title: 'Smart FAQ Chatbot', subtitle: 'Retrieval-first FAQ bot that refuses to invent answers',
    oneLiner: 'Searches a knowledge base with embeddings and answers from what it finds — and falls back to a contact message when nothing is relevant enough.',
    links: { github: GH + 'Smart-FAQ-Chatbot-RAG-Based-System' },
    stack: ['Sentence-Transformers', 'FAISS', 'all-MiniLM-L6-v2', 'Python', 'Streamlit'],
    numbers: [{ v: '3', l: 'nearest answers considered' }, { v: '0.7', l: 'similarity cut-off' }, { v: '3', l: 'modules: retrieve, generate, fallback' }],
    problem: 'Support FAQ bots that answer everything end up answering wrong. A wrong answer costs more trust than "I don\'t know".',
    approach: ['Questions and answers are embedded and indexed in FAISS. A query retrieves the top three matches and keeps only those under the distance threshold; the generator builds context from them, and if none qualify the fallback hands over to a human contact.'],
    flow: ['Question', 'Embed', 'FAISS search', 'Similarity check', 'Answer or fallback'],
    features: ['Semantic search over a JSON knowledge base', 'Threshold-based relevance filter', 'Graceful hand-off to human support', 'Modular retriever, generator and fallback'],
  },
  {
    slug: 'image-colorization', caseStudy: true, kind: ['vision'],     title: 'Image Colorization', subtitle: 'U-Net that brings colour back to black-and-white photos',
    oneLiner: 'A PyTorch U-Net trained to predict colour channels from a grayscale image, wrapped in a desktop app for loading, colourising and saving photos.',
    links: { github: GH + 'Image-Colorization-using-PyTorch-with-U-Net-Architecture-' },
    stack: ['PyTorch', 'U-Net', 'CIE Lab colour space', 'scikit-image', 'Tkinter', 'Kaggle'],
    numbers: [{ v: '50', l: 'training epochs' }, { v: '0.0095 → 0.00275', l: 'reconstruction loss' }, { v: '256 px', l: 'model input' }],
    problem: 'Colourising a photo means inventing information that isn\'t in the image. Predicting full RGB makes the network relearn brightness and edges it was already given.',
    approach: [
      'Images are converted to CIE Lab: the network receives only the L (lightness) channel and predicts the a and b colour channels, so it learns colour distribution rather than structure.',
      'A U-Net with four downsampling and four upsampling blocks uses skip connections between encoder and decoder to keep fine edges and texture. It was trained for 50 epochs on the Kaggle Landscape Pictures dataset, with loss falling from 0.0095 to 0.00275. A Tkinter app runs inference on a background thread.',
    ],
    flow: ['Grayscale photo', 'L channel', 'U-Net encoder', 'Skip connections', 'Decoder predicts a, b', 'Lab → RGB'],
    features: ['Custom PyTorch dataset with Lab conversion', 'Skip connections for detail preservation', 'Desktop app with side-by-side before and after', 'Non-blocking inference thread'],
  },
  {
    slug: 'cnn-lstm-driving', caseStudy: true, kind: ['vision', 'ml'],     title: 'Driving Decisions with CNN-LSTM', subtitle: 'Webcam model that decides stop, continue or slow down from a sequence of frames',
    oneLiner: 'A CNN reads each camera frame, an LSTM reads the last five, and the system decides an action in real time — steadier than judging one frame at a time.',
    links: { github: GH + 'Autonomous-Driving-Logic-via-CNN-LSTM-Fusion-with-Keras' },
    stack: ['TensorFlow / Keras', 'CNN', 'LSTM', 'OpenCV', 'NumPy', 'Kaggle'],
    numbers: [{ v: '5', l: 'frames of memory' }, { v: '128-d', l: 'feature vector per frame' }, { v: '3', l: 'actions: stop, continue, slow' }],
    problem: 'Single-frame classifiers flicker: one blurry frame can flip a decision. Driving needs context over time.',
    approach: [
      'A custom CNN trained on traffic signs is cut at its penultimate dense layer to produce a 128-dimensional feature vector per 32×32 frame. A rolling buffer holds the last five vectors and an LSTM turns that sequence into an action with a confidence score.',
      'Without video data, the LSTM was trained on synthetic sequences: groups of different images of the same sign, simulating a car approaching it. At run time OpenCV crops a central region of the webcam feed and overlays the decision and what the model "sees".',
    ],
    flow: ['Webcam frame', 'Centre crop 32×32', 'CNN features (128-d)', '5-frame buffer', 'LSTM', 'Action + confidence'],
    features: ['Two-stage CNN → LSTM architecture', 'Synthetic sequence generation for training', 'Real-time webcam inference', 'Colour-coded on-screen decisions'],
  },
  {
    slug: 'nexora-webar', caseStudy: true, kind: ['web'],     title: 'Nexora WebAR', subtitle: 'SaaS for publishing 3D products in augmented reality',
    oneLiner: 'Businesses upload 3D models, the platform converts them for web and iPhone AR, and customers open them in AR from a short link — with workspaces, teams, analytics and subscriptions.',
    links: { github: GH + 'Nexora-WebAR' },
    stack: ['TypeScript', 'React 18', 'Express', 'Drizzle ORM', 'PostgreSQL', 'Stripe', 'Blender pipeline', 'Tailwind'],
    numbers: [{ v: 'GLB + USDZ', l: 'outputs per model' }, { v: '20+', l: 'API routes' }, { v: 'Stripe', l: 'subscriptions' }],
    problem: 'Showing products in AR needs separate file formats for Android and iOS, hosting, and a way for customers to open them without installing an app.',
    approach: ['Uploads go into a conversion service that runs Blender headlessly to produce GLB and USDZ files plus a thumbnail, tracking each job\'s status, logs and mesh statistics. Each model gets a short link that opens the AR viewer; view events feed per-workspace analytics. Workspaces hold projects and team members, and Stripe handles subscriptions.'],
    flow: ['3D upload', 'Blender conversion', 'GLB / USDZ + thumbnail', 'Short link', 'AR viewer', 'Analytics'],
    features: ['Workspaces, projects and team roles', 'Automated 3D conversion jobs with logs', 'Short-link AR viewing', 'Analytics events and summaries', 'Stripe subscriptions', 'Admin stats'],
  },
  {
    slug: 'webar-viewer', caseStudy: true, kind: ['web'],     title: 'WebAR Model Viewer', subtitle: 'MERN app for uploading, viewing and sharing 3D models in AR',
    oneLiner: 'Upload a 3D model, preview it in the browser, launch it in AR and share it with a QR code — with accounts, an admin dashboard and view analytics.',
    links: { github: GH + 'WebAR' },
    stack: ['MongoDB', 'Express', 'React', 'Node.js', 'three.js', 'React Three Fiber', 'AWS S3', 'JWT', 'QR codes'],
    numbers: [{ v: 'QR', l: 'sharing for every model' }, { v: 'S3', l: 'model storage' }, { v: 'JWT', l: 'auth with password reset' }],
    problem: 'Sharing a 3D product with a client usually means sending a large file they can\'t open.',
    approach: ['Models upload through Multer to S3 and are rendered with React Three Fiber; an AR button hands off to the device\'s AR viewer, and a QR generator makes any model shareable from a phone. JWT auth covers registration, login and password reset, and admins see users and analytics.'],
    flow: ['Upload', 'S3 storage', 'three.js preview', 'AR launch', 'QR share', 'Analytics'],
    features: ['3D preview in the browser', 'One-tap AR launch', 'QR code sharing', 'Accounts and protected routes', 'Admin dashboard'],
  },
  // card-only projects
  { slug: 'emotion-classifier', kind: ['vision', 'ml'], title: 'Emotion Classifier', subtitle: 'CNN that tells happy from sad faces', oneLiner: 'A TensorFlow CNN trained on a Kaggle dataset I published, with data cleaning, a 70/20/10 split, and precision, recall and accuracy checks on the held-out set.', stack: ['TensorFlow', 'Keras', 'OpenCV', 'Kaggle'], links: { github: GH + 'Emotion-Classifier-Model-based-on-CNN-using-Tensorflow' } },
  { slug: 'house-price-prediction', kind: ['ml'], title: 'California House Price Predictor', subtitle: 'Regression model with a Streamlit app', oneLiner: 'Linear regression on the California housing data with cleaning, encoding and scaling; R² 0.65 and MAE about $50k on the test split, served through a Streamlit form.', stack: ['scikit-learn', 'pandas', 'joblib', 'Streamlit'], links: { github: GH + 'Price-Prediction-with-Linear-Regression' } },
  { slug: 'resume-screening-bot', kind: ['ml'], title: 'Resume Screening Bot', subtitle: 'Ranks CVs against a job description', oneLiner: 'Extracts text from uploaded PDF résumés and ranks them by TF-IDF cosine similarity to the job description, in a Flask web app.', stack: ['Flask', 'scikit-learn', 'TF-IDF', 'PyMuPDF'], links: { github: GH + 'Resume-Screening-Bot-based-on-NLP-Flask' } },
  { slug: 'text-summarizer', kind: ['agents'], title: 'Task Summarizer', subtitle: 'Flask app on Gemini 2.0 Flash', oneLiner: 'Paste a long task or brief and get a clear summary back from Gemini 2.0 Flash, through a minimal Flask interface.', stack: ['Flask', 'Gemini API', 'Python'], links: { github: GH + 'Text-Summerizer-using-Flask-based-on-Gemini-api' } },
  { slug: 'connected-operations', kind: ['automation'], title: 'Connected Operations Automation', subtitle: 'Business workflows across tools and APIs', oneLiner: 'Workflow automation that moves data between CRMs, databases, forms and AI steps through n8n, Make and webhooks, so routine hand-offs happen without anyone copying information.', stack: ['n8n', 'Make', 'Webhooks', 'APIs'], links: { contact: true } },
  { slug: 'event-manager', kind: ['web'], title: 'Event Manager', subtitle: 'Django REST + React app', oneLiner: 'Create and manage events with JWT authentication, a Django REST API on PostgreSQL and a React frontend that separates upcoming and past events.', stack: ['Django REST', 'JWT', 'PostgreSQL', 'React'], links: { github: GH + 'Event-Manager-Django-Based-Project' } },
  { slug: 'cais-website', kind: ['web'], title: 'CAIS Website', subtitle: 'COMSATS AI Society', oneLiner: 'Website for the COMSATS Artificial Intelligence Society with events and member sign-ups, built on React 19 with an Express and MongoDB backend.', stack: ['React 19', 'Vite', 'Express', 'MongoDB'], links: { github: GH + 'CAIS-Website' } },
  { slug: 'weather-dashboard', kind: ['web'], title: 'Weather Dashboard', subtitle: 'React + OpenWeather', oneLiner: 'Search any city and see current conditions, built with React hooks and the OpenWeather API.', stack: ['React', 'Vite', 'OpenWeather API'], links: { github: GH + 'Weather-Dashboard-React-Web-App' } },
  { slug: 'cpp-college-projects', kind: ['web'], title: 'C++ Systems Projects', subtitle: 'Student database, GPA calculator, ticket booking', oneLiner: 'Early object-oriented C++ programs that add, edit, store and delete records, calculate GPA and book movie tickets.', stack: ['C++', 'OOP', 'File I/O'], links: { github: GH + 'CPP-CollegeProjects' } },
];

module.exports = { profile, skills, experience, projects, KINDS };
